# WARNING:
# Do not use this file as a template for you repository TravisCI configuration
# Instead use the files under the "/sample_files" directory for that purpose.

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - VERSION="master" EXCLUDE="test_module"  # EXCLUDE usage example
  - VERSION="8.0" INCLUDE="test_module"  # INCLUDE usage example
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"  # ODOO_REPO usage example
  - VERSION="6.1"
  - VERSION=""  # test falback to script argument
  # - VERSION="6.0"  # Test script not ready for v6.0

install:
  - cp -r ../maintainer-quality-tools/ $HOME
  - mv tests/test_repo/* ./
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - git clone https://github.com/OCA/partner-contact ${HOME}/department -b 8.0 # only used if VERSION not set in env
  - travis_install_nightly 8.0 # only used if VERSION not set in env

script:
  - travis_run_flake8
  - travis_run_pylint
  - travis_run_tests 8.0 #only used if VERSION not set in env

#after_success:
#  coveralls
